In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


# Problem 1. Matrix product is calculated manually

Matrix can write by A =  $$\begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix}$$ and B = $$\begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}$$

The calculation process should be A+B, A-B, AxB, 

A+B = $$\begin{bmatrix} -1+0 & 2+2 & 3+1 \\ 4+0 & -5+2 & 6+(-8) \\ 7+2 & 8+9 & -9+(-1) \end{bmatrix} = \begin{bmatrix} -1 & 4 & 4 \\ 4 & -3 & -2 \\ 9 & 17 & -10 \end{bmatrix} $$

A-B = $$\begin{bmatrix} -1-0 & 2-2 & 3-1 \\ 4-0 & -5-2 & 6-(-8) \\ 7-2 & 8-9 & -9-(-1) \end{bmatrix} = \begin{bmatrix} -1 & 0 & 2 \\ 4 & -7 & -14 \\ 5 & -1 & -8 \end{bmatrix} $$

AXB = $$\begin{bmatrix} (-1x0) + (2x0) + (3x2) & (-1x2)+(2x2)+(3x9) & (-1x1)+(2x-8)+(3x-1)\\(4x0)+(-5x0)+(6x2) & (4x2)+(-5x2)+(6x9) & (4x1)+(-5x-8 )+(6x-1) \\ (7x0)+(8x0)+(-9x2) & (7x2)+(8x2)+(-9x9) & (7x1)+(8x-8)+(9-1) \end{bmatrix} = \begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{bmatrix} $$

# Problem 2. Calculated by numpy

In [3]:
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# Problem 3. Implementation of calcualtion of a certain element

In [79]:
print(a_ndarray)
print(b_ndarray)
result=[]
for i in range(3):
    for j in range(3):
        sum_i=0
        for k in range(3):
            sum_i=sum_i+(a_ndarray[i,k]*b_ndarray[k,j])
        result.append(sum_i)
result_matrix=np.array(result)
print(result_matrix.reshape(3,3))

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 4. function perform matrix multiplication

In [90]:
def multiply_matrix(a,b):
    result=[]
    for i in range(3):
        for j in range(3):
            sum_i=0
            for k in range(3):
                sum_i+=(a_ndarray[i,k]*b_ndarray[k,j])
            result.append(sum_i)
    result_matrix=np.array(result).reshape(3,3)
    return result_matrix

print(multiply_matrix(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 5. error handling

In [120]:
def multiply_matrix(a,b):
    if a.shape[0] == b.shape[1] :
        result=[]
        for i in range(3):
            for j in range(3):
                sum_i=0
                for k in range(3):
                    sum_i+=(a_ndarray[i,k]*b_ndarray[k,j])
                result.append(sum_i)
        result_matrix=np.array(result).reshape(3,3)
        return result_matrix
    else :
        return print("The shape a and b is not in same dimension, the column of matrix a must same with row of matrix b")

#Here i try to make new a_ndarray with different dimension, and we will try to get the result for error handling
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])

print(multiply_matrix(a_ndarray,b_ndarray))

The shape a and b is not in same dimension, the column of matrix a must same with row of matrix b
None


# Problem 6. Transpose matrix

In [103]:
print("This is the actual matrix = {}".format(a_ndarray))
print("This is the transpose matrix using np.transpose = {}".format(np.transpose(a_ndarray)))
print("This is the transpose matrix using .T = {}".format(a_ndarray.T))

This is the actual matrix = [[-1  2  3]
 [ 4 -5  6]]
This is the transpose matrix using np.transpose = [[-1  4]
 [ 2 -5]
 [ 3  6]]
This is the transpose matrix using .T = [[-1  4]
 [ 2 -5]
 [ 3  6]]
